import {NextResponse} from 'next/server';import {z} from 'zod';import {extractionSchema,fallbackExtract} from '@/lib/extract-api';
const payload=z.object({text:z.string().min(1).max(120000)});
const instruction=`You are the extraction layer for SEAL. Extract only claims visibly printed in the supplied legal notice text. Do not determine whether the notice is authentic, fraudulent, legally valid, suspicious, or trustworthy. Do not correct names, dates, court names, docket numbers, juror numbers, domains, phone numbers, addresses, spelling, payment amounts, or URLs. Do not infer missing information. Do not turn a juror/reference number into a case/docket number. A court logo, seal, layout, or official-looking language is not evidence of authenticity. Preserve exact source text for every extracted fact. If a field is absent, return the empty value required by the schema. If a field is unclear, place the raw text in uncertain_fields. Return only data matching the schema.`;
export async function POST(req:Request){try{const {text}=payload.parse(await req.json());const key=process.env.GROQ_API_KEY;if(!key)return NextResponse.json({extraction:fallbackExtract(text),mode:'DETERMINISTIC'});
 const base=process.env.GROQ_BASE_URL||'https://api.groq.com/openai/v1';if(new URL(base).hostname!=='api.groq.com')throw new Error('Provider host not allowed');
 const string={type:'string'};const array={type:'array',items:string};
 const properties={court_name:string,court_location:string,case_or_docket_number:string,juror_or_reference_number:string,judge_or_official:string,notice_date:string,reporting_date:string,phone_numbers:array,emails:array,urls:array,delivery_method:string,payment_demand:{type:'object',additionalProperties:false,properties:{amount:string,method:string,url:string},required:['amount','method','url']},threats:array,uncertain_fields:array};
 const send=async(strict:boolean)=>fetch(base+'/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.GROQ_MODEL||'openai/gpt-oss-20b',messages:[{role:'system',content:instruction},{role:'user',content:text}],temperature:0,response_format:strict?{type:'json_schema',json_schema:{name:'notice_extraction',strict:true,schema:{type:'object',additionalProperties:false,properties,required:Object.keys(properties)}}}:{type:'json_object'}}),signal:AbortSignal.timeout(18000)});
 let response=await send(true);if(!response.ok)response=await send(false);if(!response.ok)throw new Error('Model unavailable');const body=await response.json() as {choices?:{message?:{content?:string}}[]};const raw=JSON.parse(body.choices?.[0]?.message?.content||'{}');const extraction=extractionSchema.parse(raw);
 // A value absent from the supplied document must never become a verified claim.
 const present=(s:string)=>!s||text.toLowerCase().includes(s.toLowerCase());
 if(!present(extraction.court_name)||!present(extraction.court_location)||!present(extraction.juror_or_reference_number)||!present(extraction.case_or_docket_number)||extraction.phone_numbers.some(s=>!present(s))||extraction.urls.some(s=>!present(s))||extraction.emails.some(s=>!present(s))||!present(extraction.reporting_date)||!present(extraction.notice_date)||!present(extraction.payment_demand.amount)||!present(extraction.payment_demand.method)||!present(extraction.payment_demand.url)||extraction.threats.some(s=>!present(s)))throw new Error('Model invented field');
 return NextResponse.json({extraction,mode:'GROQ'});
 }catch{return NextResponse.json({error:'AI extraction was unavailable; using conservative on-device extraction.'},{status:503});}}
